### ISSUE TITLE
An error when using node.js to call "grin-wallet init -r"

### ISSUE THREAD

**Issue by xiaojay** [mimblewimble/grin-wallet#110]
the node.js code is

https://gist.github.com/xiaojay/bb4f25536faba64278a556f2be347c13

and Error is:
"Wallet command failed: Parsing IO error: Operation not supported on socket (os error 102)"
on my mac

what's wrong?

**Comment by chisa0a** [comment]
@xiaojay looks like wallet recovery is not supported over JSON-RPC. Seems dangerous to send a recovery seed over that transport. What's your use-case?

**Comment by xiaojay** [comment]
I am writing gui wallet  https://github.com/grinfans/niffler which use electron as gui.
so, seems i have to write restore in js by myself?

**Comment by garyyu** [comment]
The root cause is the [Interface crate](https://docs.rs/linefeed/0.6.0/linefeed/interface/struct.Interface.html) need open a terminal to allow user input the recovery phrases, which doesn't work in a spawned process of Node.

In `bin/cmd/wallet_args.rs`:
```
fn prompt_recovery_phrase() -> Result<ZeroingString, ParseError> {
	let interface = Arc::new(Interface::new("recover")?);
	let mut phrase = ZeroingString::from("");
	interface.set_report_signal(Signal::Interrupt, true);
	interface.set_prompt("phrase> ")?;
```

Currently we're using [linefeed](https://crates.io/crates/linefeed) **0.5.4**, not sure whether latest **0.6** will solve this problem, but you can try it.

**Comment by xiaojay** [comment]
delete Cargo.lock, and in Cargo.toml change to linefeed = "0.6.0", compiled and tried the same node code with new compiled grin-wallet.
still not work.

**Comment by yeastplume** [comment]
Seems like a node issue, but planning to address this via https://github.com/yeastplume/grin-rfcs/blob/master/grinrfc-0000-full-wallet-lifecycle.md
