### ISSUE TITLE
Can't Deserialize slate...?

### ISSUE THREAD

**Issue by Incrediblez7** [mimblewimble/grin-wallet#145]
```
grin-wallet send -m http -d https://grin.hotbit.io/353*** 1.64
```
This is a correct command, and this happened:
```
Wallet command failed: LibWallet Error: Can't Deserialize slate
```

Grin: 1.1.0
Grin-wallet: 1.1.0
OS: MacOS Mojave 10.14 Beta (18A377a)

**Comment by litterGuy** [comment]
When sending using the "/v1/wallet/owner/issue_send_tx" interface, the following error is returned.

> 20190610 06:39:09.955 INFO grin_wallet_controller::controller - Tx created: 2.551397380 grin to https://poloniex.com/public?currency=GRIN (strategy 'true')
20190610 06:39:09.955 DEBUG grin_wallet_impls::adapters::http - Posting transaction slate to https://poloniex.com/public?currency=GRIN/v1/wallet/foreign/receive_tx
20190610 06:39:10.260 ERROR grin_wallet_controller::controller - Request Error: Error { inner:
Can't Deserialize slate }

Desktop (please complete the following information):

OS: linux ubuntu 16
Version ：grin wallet： v1.1.0

**Comment by aleqx** [comment]
Can confirm this bug.  Sending to Poloniex using v1.1.0 (which works fine using v1.0.3) I get:

```
# grin-wallet send -d "https://poloniex.com/public?currency=GRIN&command=createDeposit&id=*************" 80
Wallet command failed: LibWallet Error: Can't Deserialize slate
```

I also tried forcing v1 slate to no avail:

```
# grin-wallet send -v 1 -d "https://poloniex.com/public?currency=GRIN&command=createDeposit&id=*************" 80
Wallet command failed: LibWallet Error: Can't Deserialize slate
```

Sending using slate files (`-m file -d file.tx -v 1`) works fine.

**Comment by Incrediblez7** [comment]
I tried to use a GUI wallet, called `Niffler`. When I try to create transaction on `Niffler`, the transaction goes through without any error. 
Github repository: [https://github.com/grinfans/Niffler](url)
It seems they are using `Grin v1.1.0`.

**Comment by quentinlesceller** [comment]
I have the same issue and I guess Poloniex changed something on their side. Will try to contact them.

**Comment by aleqx** [comment]
Well, Poloniex seems totally screwed right now ... 1.0.2 deposits no longer work either.

Trying http gives:

```
grin wallet send -d "https://poloniex.com/public?currency=GRIN&command=createDeposit&id=6b21bfcb-9b24-493a-858c-659e1ecc5c7a" 50.0
Password:
20190614 21:33:38.205 ERROR grin_wallet::adapters::http - Posting transaction slate (is recipient listening?): ResponseError error: Cannot parse response
Wallet command failed: LibWallet Error: Client Callback Error: Posting transaction slate (is recipient listening?): ResponseError error: Cannot parse response
```

And trying uploading a slate file gives:
![](https://i.gyazo.com/e01eb2d20086c1f028996eb1a1070ab9.png)

**Comment by DavidBurkett** [comment]
@aleqx I informed them of these issues May 25th (20 days ago). They took 10 days to respond and tell me I was wrong, everything is working fine. I've followed up twice since. Today I got the response: `I have escalated your comments to our engineering manager and product manager to evaluate your response.`

**Comment by aleqx** [comment]
Well I did make successful deposits in the past week, the last one today using 1.0.2 (see below) which is now failing ...

![](https://i.gyazo.com/562ecd66ea07b6fded5ecd6e8b20678a.png)

**Comment by xiaojay** [comment]
> I tried to use a GUI wallet, called `Niffler`. When I try to create transaction on `Niffler`, the transaction goes through without any error.
> Github repository: [https://github.com/grinfans/Niffler](url) 
> It seems they are using `Grin v1.1.0`.

Niffler still use the grin1.02 way to send grin.
see https://github.com/grinfans/Niffler/blob/gw1.1.0/src/renderer/components/HttpSend.vue#L178
it works on most of exchanges.
However, I don't know why it can not work on Poloniex.

**Comment by taoteh1221** [comment]
Seems like @aleqx is correct, can confirm slate file method Sending using slate files (-m file -d file.tx -v 1) no longer works at poloniex, just so everyone is aware. At least on ubuntu 18 / chromium.

**Comment by yeastplume** [comment]
These are exchange issues (which we take some responsibility for). Please see the announcement regarding these kinds of issues here: https://www.grin-forum.org/t/addressing-recent-transaction-difficulties/5339/5 

Also, tell all your friends and family to update to Grin v2.0.0 as soon as it's available!

**Comment by taoteh1221** [comment]
@yeastplume Thanks for the response, good luck with the HF.

**Comment by aleqx** [comment]
Poloniex still doesn't accept any deposits from 1.1.0 -- either file or http based.

**Comment by aleqx** [comment]
> Poloniex still doesn't accept any deposits from 1.1.0 -- either file or http based. Just tried both.
> Doesn't matter which slate version I use (v0, v1, v2).

Most likely due to this:

> BREAKING CHANGE: All u64 fields in the slate are now sent as strings for compatibility reasons (64 bit literals are not valid JSON). Applications still using SlateV0 may have to adjust accordingly.

The above change should not have been implemented for v0 and v1 slates, as it was bound to break exchange compatibility and affect the ecosystem -- something to keep in mind for the future @yeastplume 

Still, 1.1.0-beta has been out since April 1 so Poloniex has little to no excuse too ... especially given they still refuse to fix it after being reported to them weeks ago.

**Comment by aleqx** [comment]
Actually, it's not that. I figured out the syntax Poloniex is expecting and what exactly fails, and then manually edited the .json produced by 1.1.0 to "fix" it for Poloniex deposits. Can confirm that the following works:

The problem is that 1.1.0 is outputting `.tx.body.kernels[].features="Plain",` and `.tx.body.kernels[].lock_height=0` and also `.lock_height=0`

Poloniex expects `.tx.body.kernels[].features="HeightLocked",` and `.tx.body.kernels[].lock_height=.height` and also `.lock_height=.height`

The following small shell script should work (use at your own risk -- though the worst it could happen is Poloniex saying "invalid file")

```bash
#!/bin/bash
height=$(grep -Po '(?<="height":)\d+' "$1")
sed -E 's/"kernels":\[\{"features":"Plain"/"kernels":\[\{"features":"HeightLocked"/;s/"lock_height":0/"lock_height":'$height'/g' "$1"
```

save the above into `uncrap-polo.sh` then produce your slate file using `grin-wallet -m file -d polo.tx -v 1 1.0` then mangle it using `bash uncrap-polo.sh polo.tx > polo-uncrapped.tx`

You're welcome, Poloniex ...

**Comment by DavidBurkett** [comment]
Great find! Send Poloniex a bill for your work.

**Comment by aleqx** [comment]
> Great find! Send Poloniex a bill for your work.

Haha ... ok, I edited my post above and added my ETH and BTC wallets. Let's see if Poloniex is up for a publicity stunt :smile:

**Comment by aleqx** [comment]
https://twitter.com/aleqx3/status/1144370126898290688

If Poloniex sends me anything then I'll pass it on to the Grin project.
