### ISSUE TITLE
Wallet seed is based on BIP39 entropy as opposed to seed

### ISSUE THREAD

**Issue by yeastplume** [mimblewimble/grin-wallet#213]
Currently, the wallet's seed is being generated directly from BIP39 entropy, whereas it should be being fed through 2048 rounds of PBKDF2 with a password (even if blank). This should be rectified for new wallets (with a simple call to 'to seed'), with a mechanism to ensure older mnemonics can still be used to restore.

**Comment by yeastplume** [comment]
As discussed in the wallet dev channel, this is unfortunate that we're not properly adhering to the BIP39 spec, but there is no way to migrate wallets to this change without a severe mess. In short:

* Both the entropy and PBKDF2(entropy) are equally valid wallet seeds. If a user were to attempt to restore from a phrase in a wallet that had support for PBKDF2 + Legacy, a restore would need to scan the entire chain for both versions to determine which that particular seed should support. This would become even messier if a user recovered from seed with a phrase, then did a few transactions, then did a further check to find older output.
* There are no particular security benefits to the PBKDF2 version over the entropy (we're not using a BIP39 passphrase)

We do need to document the recovery process somewhere, particularly as it's non standard. I'll open a separate issue for that.

**Comment by Anynomouss** [comment]
I was thinking to implement the option for BIP39 password protected wallets for grin when I get around to it. 
Since these wallets would all be newly generated, I would propose to make these password protected wallets adhere to the BIP39 standard. So use the entropy + password PBKDF2 hashing with the password.
This would also imply that for these new password protected wallets, the user cannot run _grin.exe recover_ since the PBKDF2 hashing cannot be reverted. On the plus side, these wallets would adhere to BIP39.
