### ISSUE TITLE
doctests in owner.rs failing silently during setup and not testing the documented functions

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin-wallet#415]
Related: #414 

In `doctest_helper_setup_doc_env` we call `open_wallet()` but this fails as we have not yet created a wallet.
So the setup code fails for every doctest that uses it.
This causes several tests to not actually test what they appear to be testing due to the way the tests are written.

Both `tx_lock_outputs` and `verify_payment_proof` appear to fail on CI regularly but they are not actually running correctly locally either.

I don't fully understand why they cause CI to fail while effectively failing silently locally, but the tests are not exercising the api.

This appears to affect many doctests in `owner.rs`. We should verify these all work as expected once we have a fix for this.
We should also check the other files that contain doctests to ensure these behave as expected also.

**Comment by yeastplume** [comment]
This is known and intentional. The doctests in `owner.rs` and `foreign.rs` are just intended to compile to ensure the documentation matches the code. The functions are thoroughly exercised via the json-rpc tests in `owner_rpc.js` and `foreign_rpc.js`, so having both APIs setup and execute tests would be redundant, particularly given the amount of time they already take during CI.

We did have resource issues on CI VMs causing apparent random failures that were alleviated by manually cleaning up wallet environment simulation threads, will have a look at the CI failures now

**Comment by antiochp** [comment]
Closing. 
Feels like there _must_ be a clearer and simpler way of setting up the test if these are purely for docs. There is a large amount of hidden code setting up each test and the cost of maintaining this feels like it potentially defeats the purpose of keeping the docs accurate.
This is a different discussion though.
