### ISSUE TITLE
API does not support reposting

### ISSUE THREAD

**Issue by DavidBurkett** [mimblewimble/grin-wallet#452]
The post_tx API requires a slate, rather than just a transaction. This means that it's not possible to repost a transaction later if you only have the transaction ID. The repost wallet command looks up the stored transaction, and then creates a Slate from the transaction: https://github.com/mimblewimble/grin-wallet/blob/66e2d0d5ae3ed36c70e301bb9d793c2620502e4a/controller/src/command.rs#L1263-L1264

API consumers should not have to know how to create slates, especially since the structure changes frequently. Instead, there should be a simple API to repost a transaction given a tx_id or slate_uuid.

**Comment by yeastplume** [comment]
Yes, looks like it's become a bit muddled. 

* The entire command-line `repost` functionality is implemented too far up, it should be within the API.
* I think `post_tx` is fine right now, taking a Slate to cover cases where you want to post from a saved Slatepack (or file containing one).
`get_stored_tx` in the API is returning a raw Transaction object given a Transaction ID.

So how about:
* `get_stored_tx` accepts either a transaction id or slate uuid
* `get_stored_tx` to return a Slate instead of a raw transaction (which is odd, cause there's nowhere else in the API where consumers are expected to act on raw transactions). Think this is the best approach for consistency

So the workflow is just to call `get_stored_tx` with a UUID or tx_id, then just call `post_tx` with the result.

**Comment by DavidBurkett** [comment]
This could work, if we're OK with breaking backward-compatibility. If we're not, we could add a field to the `get_stored_tx` request that, when set, returns a slate instead of tx.

**Comment by yeastplume** [comment]
I'm okay with small breaking changes like this at major version increment time. Will think a bit more before implementing but I think it's odd to have a raw transaction object exposed anywhere.

**Comment by yeastplume** [comment]
Handled via #454
