### ISSUE TITLE
Accounts do not get recovered when the grin-wallet is recovered with passphrase

### ISSUE THREAD

**Issue by shuan9-polo** [mimblewimble/grin-wallet#594]
**Describe the bug**
Accounts are not recovered after the grin-wallet is recovered.

**To Reproduce**
1. run `grin-wallet init` to initialize and enter the password
2. copy out the printed passphrase
3. run `grin-wallet account -c test` and enter the password
4. run `grin-wallet account` to confirm the account test has been created
5. change to another directory and run `grin-wallet init -hr`
6. copy the passphrase saved in step 2 and paste it here
7. when the recovery is completed, run `grin-wallet account`
8. only account default can be seen

**Expected behavior**
Account test should also be seen in step 8

**Screenshots**
![image](https://user-images.githubusercontent.com/73355381/110816772-9af7d200-82c6-11eb-9e18-13a9048b917c.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.7

Could you please take a look and suggest if this is a bug or limitation or I missed some steps?

**Comment by shuan9-polo** [comment]
May I know if there is any update with this issue? Thanks.

**Comment by deevope** [comment]
Before the step 7, you need to run `grin-wallet scan`, after that it will list account(s) only if it contains some Grin.

**Comment by phyro** [comment]
@shuan9-polo does this resolve your issue?

**Comment by shuan9-polo** [comment]
I think `grin-wallet info` will trigger the scan as I observed the scanning progress logged after the execution. But I think I would not be able to see the the other accounts since there is no grin in that account.

**Comment by deevope** [comment]
@shuan9-polo Indeed `grin-wallet info`, will make a scan and will look as well if others accounts outputs exist in the UTXO set. 

And sorry, if I didn't give you enough details, but for a given seed, you will have always if you create several accounts, the same `Parent Key` for each account. Account creation on the grin-wallet is deterministic as it follows the BIP32 Derivation path. 
To be clear, if you need to recover the same 5th account of your old wallet even if there's no grin in it for example, whatever is the reason for that, you can do it manually, you'll just have to create 5 account until you hit the parent derivation path `m/4/0`, and you will get exactly the same account you had before. 

But right now, you can't recover _automatically_ empty account. I guess we could add more maneuverability over them like, in case of seed recover, add a flag to create as well the `m/4/0` account or a range of account even if they are empty, add the ability to rename them etc... 

Right now, I don't see the real necessity of it as grin deletes spent output after 7 days, but if you are really looking for it, let the grin devs community knows what you would expect here otherwise if everything is fine and your initial problem is fixed, you can close the issue.👍

**Comment by shuan9-polo** [comment]
Hi @deevope, thanks for providing all these information and it's very helpful. I created the other account only to validate if my restore is successful or not. As I don't have any grin to test with, I thought this may also work for the validation as a workaround (but it seems not). But anyway, thanks again for helping out and I will close this ticket.

**Comment by phyro** [comment]
great! thanks to both for resolving it and don't forget to close the issue @shuan9-polo  :+1:
