### ISSUE TITLE
Unknown transaction appears as awaiting finalization

### ISSUE THREAD

**Issue by johndavies24** [mimblewimble/grin-wallet#619]
**Describe the bug**
An unknown pending tx (awaiting finalization) appeared in the output of ./grin-wallet info.  The wallet stopped responding properly over tor after this occurred.

I could not find any entry that corresponded to the pending tx value when I looked through ./grin-wallet txs.

I tried ./grin-wallet repost and got the error message that I copied below.

Then I killed listen, rebooted node and ran ./grin-wallet scan and my wallet was able to transact over tor, but the mysterious tx was still awaiting finalization.  I tried the repost command again and got the same error as below.

**Expected behavior**
I expect all transactions to appear in my transaction log and do not expect to see an unknown tx awaiting finalization and no evidence of this tx in my tx log.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version Grin 5.1.0 Grin-wallet 5.0.3

**Error message**

20210521 23:27:07.155 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/cmd/wallet_args.rs:831   0: grin_util::logger::send_panic_to_log::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:497
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495
   5: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92
   6: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50
   7: grin_wallet::cmd::wallet_args::parse_repost_args
   8: grin_wallet::cmd::wallet_args::parse_and_execute
   9: grin_wallet::cmd::wallet_args::wallet_command
  10: grin_wallet::cmd::wallet::wallet_command
  11: grin_wallet::real_main
  12: grin_wallet::main
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: std::rt::lang_start::{{closure}}
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259
      std::panicking::try::do_call
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381
      std::panicking::try
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396
      std::rt::lang_start_internal
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51
  16: main
  17: __libc_start_main
  18: _start

Thread 'main' panicked with message:
"called `Option::unwrap()` on a `None` value"

**Comment by cliik** [comment]
This looks like someone attempted to send you coins, but failed/aborted before finalizing. Reposting will not fix this, because your wallet has nothing to post. The transaction can only be finalized by the sender.

afaict, you have a few options:
1) contact the sender (if you know who it was) and ask them to repost or try again
2) you may be able to 'cancel' that transaction, if you do not know the sender and wish to clear it from your output list

**Comment by cliik** [comment]
@phyro can we close this? The OP seems away and what he reports isn't actually a bug (unless he is able to provide more details)

**Comment by phyro** [comment]
The error during the `repost` call was because no `id` parameter was passed. A fix for a nicer message here seems to be a low hanging fruit to get onboarded. I was looking a bit through the code and it seems very hard to deduce what went wrong that got you in this state @johndavies24 without further info about what sequence of commands were run that produced this. I'm going to close this now to reduce the backlog, but if you ever encounter this again, do tell which commands you ran and I can take a look to see if I can catch a case that produces this.
