### ISSUE TITLE
Deprecate http listener for external addresses

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-wallet#66]
Deprecate http listeners for external addresses due to it being insecure and exposing the transacting parties to unnecessarily easy attacks.

Blocked until a convincing better alternative is proposed for transaction building.

---
_Apr 02 2020 edit: Renaming and editing description and using to track for v4.0.0_

**Comment by hitchcott** [comment]
> https is enforced
> fully deprecate http

In some cases it might be ok to use HTTP; I don't think it should be discontinued entirely (if that's the suggestion).

- Two clients are on the same machine (sending to localhost)
- Two clients are communicating on a trusted network (e.g. VPN, VPC, LAN)
- You have some kind of proxy handling transport security somewhere else

**Comment by aleqx** [comment]
I'm late to the party, but I've been reading this thread with interest. 

We must all agree that as great as GRIN is, the ease of use has been a turnoff. I for one learnt to respect (rather than ignore/reject) thy clueless folk -- they are the ones who add the necessary pressure to innovate, just like gamers basically pushed Nvidia to become the giant it is today. Grin most definitely needs a much more seamless and more reliable way of sending and receiving if it is to be more widely adopted.

At the same time, I fully agree with the security arguments. In fact, ever since GRIN has started being talked about more widely last year, particularly after launch this year, I've been amazed at how little public- and user expressed concern there is for security and the trivial-to-implement MITM attacks on grin tx's. I recall watching how after launch hoardes of miners were sending GRIN to IP addresses of new anonymous chinese exchanges over http, addresses given out on Telegram channels etc. Now we see a proliferation of public proxy services for dyn-ip wallets to receive funds. It's gringy and sets dangerous precedents. A secure, professional, non-hacky solution is needed or else GRIN risks not being taken seriously long term, after the hippie phase subsides.

At first I was going to suggest "just embed openpgp" and self signed certs (basically @casey's proposal) but I think @ignopeverell's suggestion is the simplest and best, and also addresses ease of use. Was there any progress on this? 

Genuine question: Why isn't this top priority? I agree with @hashmap that the longer http:// is allowed to be used, the more the people will get used to it as the norm, making a shift to a proper solution more difficult (and deprecating things abruptly is never a good idea, especially in this context with exchanges floating around).

While GRIN has stated from the very beginning that it's just an experimental tech, I think we have to agree that the users's perception is sometimes more important than truth (like in politics, bleh) ... if they think GRIN is the next BTC and really want ease of use, security, value, etc, then someone will come up with solutions to meet that pressure. GRIN may very well become vital despite initial intentions.

p.s. Long term ipv6 may make send/receive easier still.

**Comment by yeastplume** [comment]
@aleqx There's work currently underway on i2p support, which we think will be a long-term solution. I agree the situation isn't ideal, but MITM attacks on slates aren't quite as easy as you suggest. Most of the info on slates (the transaction info) is considered 'Public', and due to the Schnorr signature scheme nobody can really modify much within the slate without knowledge of the private keys. There is the possibility of leaking total transaction amounts, however, which I agree isn't great.

Have a few ideas on protocols that might make transacting easier and more secure, but would like to see the wallet subteam formed first to have these explorations.

**Comment by aleqx** [comment]
Agreed. I was referring to a diversion rather than MITM. Simply put, right now whoever gets the slate gets the dosh (intercept the sent slate, finalize and return receive slate). Plain http makes that scary. A disgruntled sysadmin, ISP employee, etc sitting in the comms chain could once decide to just receive the tx themselves and say thanks very much.

**Comment by OctoberSouth** [comment]
Error reporting using grin-wallet send -d "xxxxxx" 0.001 ,log is (error grin_wallet_impls::adapters:http - performing version check (is recipient listening?):request error:cannot make reclsed),why is this

**Comment by lehnberg** [comment]
This ticket has been refined and repurposed to comply with the target of 4.0.0 as discussed in the  [Mar 31 dev meeting](https://github.com/mimblewimble/grin-pm/blob/master/notes/20200331-meeting-development.md#4-planning-v400).

**Comment by GHLover** [comment]
Whatever you do please do not deprecate HTTP for localhost listeners at a minimum. Currently, I like the ability to create proxies in front of the internal HTTP listener. Please also do not disable sending to an HTTPS address.

**Comment by GHLover** [comment]
Also, IMO, any requirement in the future of Grin such as the necessity for i2p or tor daemon should be part of the single Grin binary.

Requiring users to setup Tor or I2P just to utilize Grin will guarantee that Grin never has a use-case. Barriers to entry should be decreasing, not increasing, IMO.

**Comment by aleqx** [comment]
I would also like to keep http for localhost as I want Apache in front to reverseproxy and handle https there more easily.

> Barriers to entry should be decreasing, not increasing, IMO.

I've been saying the same for a while. I'm sure the devs are well aware of the aspects regarding usability. Sadly, Grin was launched in a state usable only by experts (give or take) and thus has set an undesired tone and impression. More than a year later it looks to me there adoption and usage is decreasing, that is once you filter out the fanatics -- those who claim Grin is the next BTC or those who claim "BTC also needed years to catch on" (missing the point that there was no precedent or alternative for BTC).

**Comment by lehnberg** [comment]
Deprecation message was introduced as part of  https://github.com/mimblewimble/grin-wallet/pull/423, due to be released as  v4.0.0 in 30 days time. Closing this issue.
