### ISSUE TITLE
Wrong amount on repeated transaction creation after cancel on pay

### ISSUE THREAD

**Issue by ardocrat** [mimblewimble/grin-wallet#706]
Wallet is increasing amount of new created tx after previous cancel for value of requested amount. It also increases it with every attempt for value of previous amount + requested amount.

Reproduce:
```
# Put invoice from receiver
grin-wallet pay

# See tx at list
grin-wallet txs

# Cancel created tx
grin-wallet cancel -t  

# Put same invoice from receiver
grin-wallet pay

# Amount increased
grin-wallet txs
```

**Comment by Anynomouss** [comment]
Quite interesting to see what bug causes to increase the amount with v* numbers_of_tries. Perhaps each times the same output is created with a new key and retrieved double since it links to the same input. If that is the case, probably also double change outputs are created. Of-course this would make the transaction invalid since trying to spend an output two times the same time would mean sum(values*H)!=0, meaning the kernel excess will not be valid pub-key of G.
